
comparisons:
  - name: zone1_vs_zone2
    protocol: pe
    sample_sheet: /home/lisa/multimodal-ngs-course-2026/pipelines/rna-seq-zone-specific-3t-seq/3t-seq/sample_sheets/zone1_vs_zone2_samplesheet.csv
    strandedness: 1
    trimmomatic: "ILLUMINACLIP:$CONDA_PREFIX/share/trimmomatic/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 CROP:50 MINLEN:36"
    deseq2:
      test: Wald
      variable: zone
      reference_level: zone2
    
  - name: zone1_vs_zone5
    protocol: pe
    sample_sheet: /home/lisa/multimodal-ngs-course-2026/pipelines/rna-seq-zone-specific-3t-seq/3t-seq/sample_sheets/zone1_vs_zone5_samplesheet.csv
    strandedness: 1
    trimmomatic: "ILLUMINACLIP:$CONDA_PREFIX/share/trimmomatic/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 CROP:50 MINLEN:36"
    deseq2:
      test: Wald
      variable: zone
      reference_level: zone5


disable_TE_analysis: true
disable_salmonTE_analysis: true
disable_tRNA_analysis: true

tRNA_quantification:
  method: "mim-tRNA-seq" # Options: "standard" or "mim-tRNA-seq"
  mimseq_params:
    max_mismatches: 0.1
    cluster_identity: 0.95
    min_cov: 10

globals:
  results_folder: /home/lisa/multimodal-ngs-course-2026/pipelines/rna-seq-zone-specific-3t-seq/3t-seq/results

genome:
  label: mm10
  annotation_type: gencode

  # URL to GtRNAdb files
  gtrnadb_url: http://gtrnadb.ucsc.edu/genomes/eukaryota/Hsapi38/hg38-tRNAs.tar.gz
  #gtrnadb_bed: ../../../data/references/tRNA/mm10-tRNAs.bed
